[book]
authors = ["authors of flutter_rust_bridge, see GitHub README.md for detailed contributions", "trdthg <trdthg@outlook.com>"]
language = "zh"
multilingual = false
src = "src"
title = "flutter_rust_bridge"
