[book]
authors = ["trdthg <trdthg@outlook.com>", "authors of flutter_rust_bridge, see GitHub README.md for detailed contributions"]
language = "zh"
multilingual = false
src = "src"
title = "flutter_rust_bridge"
